// js/constants.js
const GRID_SIZE = 60;   // half the previous 120px → twice as dense grid

const SEARCH_FILTERS = [
  'FOCUS_FILTER_MANPOWER','FOCUS_FILTER_INDUSTRY','FOCUS_FILTER_STABILITY',
  'FOCUS_FILTER_WAR_SUPPORT','FOCUS_FILTER_RESEARCH','FOCUS_FILTER_POLITICAL',
  'FOCUS_FILTER_MILITARY','FOCUS_FILTER_NAVY','FOCUS_FILTER_AIR_FORCE',
];

const DEFAULT_ICON = 'GFX_goal_unknown';