// js/constants.js
const GRID_SIZE = 60;

const SEARCH_FILTERS = [
  'FOCUS_FILTER_MANPOWER','FOCUS_FILTER_INDUSTRY','FOCUS_FILTER_STABILITY',
  'FOCUS_FILTER_WAR_SUPPORT','FOCUS_FILTER_RESEARCH','FOCUS_FILTER_POLITICAL',
  'FOCUS_FILTER_MILITARY','FOCUS_FILTER_NAVY','FOCUS_FILTER_AIR_FORCE',
];

const DEFAULT_ICON = 'GFX_goal_unknown';

// Focus types
const FOCUS_TYPE_NORMAL = 'focus';
const FOCUS_TYPE_SHARED = 'shared_focus';
const FOCUS_TYPE_JOINT  = 'joint_focus';
